### ISSUE TITLE
Wallet.build_obtain_token_url не задает параметр "&response_type=code" в URL запроса авторизации

### ISSUE THREAD

**Issue by Sovetnikov** [yandex-money/yandex-money-sdk-python#3]
Wallet.build_obtain_token_url() не задает response_type, который требуется, иначе не работает и выдается чудное сообщение "Этому приложению отказано в доступе. Свяжитесь с его разработчиком и укажите сведения об ошибке (invalid_request)"
Поправьте.

**Comment by romkavt** [comment]
Has been fixed by https://github.com/yandex-money/yandex-money-sdk-python/pull/2
